### ISSUE TITLE
Unable to find a specification for `KUIPopOver`

### ISSUE THREAD

**Issue by bhavneet0812** [Kofktu/KUIPopOver#2]
This error was come up when I tried to install KUIPopOver through Pods.

**Comment by Kofktu** [comment]
@bhavneet0812 hi

**Comment by Kofktu** [comment]
hi~
try to
repo update master

**Comment by Kofktu** [comment]
@bhavneet0812 
hi, 
try to cocoapods repository update
```ruby
pod repo update
```

and change to Podfile

- Swift3
```ruby
pod 'KUIPopOver', '0.0.4'
```

- Swift4
```ruby
pod 'KUIPopOver', '~> 1.0.0'
```

**Comment by bhavneet0812** [comment]
Thanks.
