### ISSUE TITLE
Can I hide the arrow?

### ISSUE THREAD

**Issue by JeromeTW** [Kofktu/KUIPopOver#7]
Thanks for the great project.

Can I hide the arrow? Just show the custom view is good for me.

**Comment by JeromeTW** [comment]
I found answer here.
https://stackoverflow.com/a/36621494/4593553

**Comment by Kofktu** [comment]
@JeromeTW Hi,
KUIPopOver support arrow hide [v0.0.4](https://github.com/Kofktu/KUIPopOver/releases/tag/0.0.4)

```swift
var arrowDirection: UIPopoverArrowDirection {
    return .none
}
```
