### ISSUE TITLE
Fill UITableView??

### ISSUE THREAD

**Issue by fgrosjean** [Kofktu/KUIPopOver#8]
Anyway to populate a table (pass values? completion?) after the popover has been presented?

**Comment by Kofktu** [comment]
@fgrosjean 
Yes, 
if you use autolayout, set constant tableview width

**Comment by fgrosjean** [comment]
Mmmm... let's see if I can explain myself better. Native popovers are called with:
present(popOverViewController, animated: true, **completion**: nil)

but KUIPopOver only has:
`customViewController.showPopover(sourceView: sender, sourceRect: sender.bounds)
customViewController.showPopover(barButtonItem: sender)
customViewController.showPopover(withNavigationController: sender, sourceRect: sender.bounds)
 `

No COMPLETION for passing data to the presented view controller.

**Comment by Kofktu** [comment]
@fgrosjean 
ah, you want show completion closure?
hmm.. I will update it this week!
or
welcome to PR!!! ^^

**Comment by fgrosjean** [comment]
@Kofktu Really nice library you got here. Thank you!

**Comment by Kofktu** [comment]
@fgrosjean 
CocoaPods has been updated.

![2018-04-18 11 23 48](https://user-images.githubusercontent.com/1860205/38938044-9c1ff648-435f-11e8-9351-ffc796638d08.png)

**Comment by wdcurry** [comment]
The completion handler fires off immediately upon showing, which seems rather not expected. Looking into why but using basic signature as provided.
